checker/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from .views import Check
import re
import login.views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$',Check.as_view()),
	url(r'^login/', login.views.user_login,name='login'),
	url(r'^logout/', login.views.logout_page	),
	url(r'^contact	/', login.views.logout_page	),
	url(r'^register/', login.views.register),
    url(r'^plagchecker',views.geturls,name='geturls'),
	url(r'^upload/$', views.model_form_upload, name='model_form_upload'),
	url(r'^show/(.*)/$',views.show,name='show'),
	url(r'^dashboard/',views.dashboard,name='dashboard')
	]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plagiarismchecker/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from api.resources import DataResource,DocumentResource

data_resource = DataResource()
document_resource = DocumentResource()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('checker.urls',namespace='checker',app_name='checker')),
    url(r'^api/', include(data_resource.urls)),
    url(r'^api/', include(document_resource.urls)),
    
]

checker/models.py
import uuid
import os
from django.db import models
from django.contrib.auth.models import User
randomid = uuid.uuid4()
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (randomid, ext)
    return os.path.join('documents/', filename)


class Data(models.Model):
    data = models.TextField()
    user = models.ForeignKey(User,null=True)
    def __str__(self):
        return self.data

	# keywords = models.CharField(max_length=500)
#
# class Document(models.Model):
    #document = models.FileField(upload_to=get_file_path)

	#uploaded_at = models.DateTimeField(auto_now_add=True)
class Document(models.Model):

    user = models.ForeignKey(User,null=True)
    result = models.DecimalField(max_digits=50,decimal_places=5,null=True)

    description = models.CharField(max_length=255, blank=True, default='')
    document = models.CharField(max_length=255, )
    uploaded_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.document

checker/forms.py
from django import forms
from .models import Data,Document
class DataForm(forms.ModelForm):
	# post = forms.CharField(max_length=280)

	class Meta:
		model = Data
		fields = ('data',)

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document', )

checker/views.py
from django.core.urlresolvers import reverse
import PyPDF2
from django.shortcuts import render
import json
from django.contrib.auth.decorators import login_required
from random import randint
import difflib
import datetime
from .forms import DataForm,DocumentForm
from urllib.parse import urlencode, urlparse, parse_qs
import re
from django.core.files.storage import FileSystemStorage
from lxml.html import fromstring
from requests import get
import requests
from bs4 import BeautifulSoup
import io
from os.path import splitext
import random
import re, math
from collections import Counter
from django.http import HttpResponseRedirect
from .models import Document,Data,randomid
from django.views import View

MAX_RETRIES = 20
session = requests.Session()
adapter = requests.adapters.HTTPAdapter(max_retries=MAX_RETRIES)
session.mount('https://', adapter)
session.mount('http://', adapter)

browsers = [
            'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.6) Gecko/2009011913 Firefox/3.0.6',
            'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.0.6) Gecko/2009011912 Firefox/3.0.6',
            'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.6) Gecko/2009011913 Firefox/3.0.6 (.NET CLR 3.5.30729)',
            'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.6) Gecko/2009020911 Ubuntu/8.10 (intrepid) Firefox/3.0.6',
            'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.6) Gecko/2009011913 Firefox/3.0.6',
            'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.6) Gecko/2009011913 Firefox/3.0.6 (.NET CLR 3.5.30729)',
            'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/1.0.154.48 Safari/525.19',
            'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30; .NET CLR 3.0.04506.648)',
            'Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.0.6) Gecko/2009020911 Ubuntu/8.10 (intrepid) Firefox/3.0.6',
            'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.5) Gecko/2008121621 Ubuntu/8.04 (hardy) Firefox/3.0.5',
            'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_6; en-us) AppleWebKit/525.27.1 (KHTML, like Gecko) Version/3.2.1 Safari/525.27.1',
            'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 1.1.4322)',
            'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)',
            'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)'
            'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0',
            ]
WORD = re.compile(r'\w+')
headers={
	'User-Agent': browsers[random.randint(0, len(browsers) - 1)],
	'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
	'Accept-Language': 'en-us,en;q=0.5'
	}
def get_cosine(vec1, vec2):
     intersection = set(vec1.keys()) & set(vec2.keys())
     numerator = sum([vec1[x] * vec2[x] for x in intersection])

     sum1 = sum([vec1[x]**2 for x in vec1.keys()])
     sum2 = sum([vec2[x]**2 for x in vec2.keys()])
     denominator = math.sqrt(sum1) * math.sqrt(sum2)

     if not denominator:
        return 0.0
     else:
         d1 = float(numerator) / denominator
         #print(d1)
         return d1
def text_to_vector(text):
     words = WORD.findall(text)
     return Counter(words)
def calplag(file1_data,file2_data):

    text1 = file1_data
    text2  = file2_data
    vector1 = text_to_vector(text1)
    vector2 = text_to_vector(text2)
    cosine = get_cosine(vector1, vector2)
    #print ('Cosine:', cosine)
    return cosine




# def dataextract(urllist,textss):
#     f = io.open('file1.txt','w', encoding="utf-8")
#     f.truncate()
#     f.close()
#     toplist = urllist[:1]
#     for l in toplist:

#         #print(l)
#         if (l!='/' and len(l)>2):
#             html = get('http://%s'%(l),verify = False,headers = headers).text
#             soup = BeautifulSoup(html)
#             # kill all script and style elements
#             for script in soup(["script", "style"]):
#                 script.extract()
#                 # get text
#             text = soup.get_text()
#             # break into lines and remove leading and trailing space on each
#             lines = (line.strip() for line in text.splitlines())
#             # break multi-headlines into a line each
#             chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
#             # drop blank lines
#             text = '\n'.join(chunk for chunk in chunks if chunk)
#             z = io.open('file1.txt','a', encoding="utf-8")
#             z.write(text)
#             z.close()
#             #print(text)
#     d1 = io.open('file1.txt','r', encoding="utf-8")

#     file1_data = d1.read()
#     file2_data = textss
#     similarity_ratio = calplag(file1_data,file2_data)
#     #similarity_ratio = SequenceMatcher(None,file1_data,file2_data).ratio()
#     d1.close()

#     return similarity_ratio


def dataextract(urllist,textss,x):
    sentenceslist = []
    datalist = []
    similarity_ratio = []
    inptextsent = []
    randomfiles = []


    m = re.split(r'(?<=[^A-Z].[.?]) +(?=[A-Z])', textss)
    for senten in m:
        sentenceslist.append(senten)
    if x!=1:
    	toplist = urllist[:5]
    else:
    	toplist = urllist[:1]
    for l in toplist:
        f = io.open('file1.txt','w', encoding="utf-8")
        f.truncate()
        f.close()
        rad = randint(0, 10000000000000)
        randomfiles.append(rad)

        #print(l)
        if (l!='/' and len(l)>2):
            parsed = urlparse(l)
            root, ext = splitext(parsed.path)
            if ext=='.pdf':
                html = get('http://%s'%(l),verify = False,headers = headers,stream=True)
                with open("syed.pdf","wb") as pdf:
                    for chunk in html.iter_content(chunk_size=1024):

                         # writing one chunk at a time to pdf file
                         if chunk:
                             pdf.write(chunk)
                    pdf.close()
                    docdata = open('syed.pdf','rb')
                    pdfReader = PyPDF2.PdfFileReader(docdata)

                    num_pages = pdfReader.numPages
                    count = 0
                    text = ""

                    while count < num_pages:
                        pageObj = pdfReader.getPage(count)
                        count +=1
                        text += pageObj.extractText()

                    z = io.open('file1.txt','a', encoding="utf-8")
                    z.write(text)
                    z.close()
                    z = io.open('media/%d.txt'%(rad),'a', encoding="utf-8")
                    z.write(text)
                    z.close()
                    datalist.append(text)
                    m = re.split(r'(?<=[^A-Z].[.?]) +(?=[A-Z])', text)
                    for senten in m:
                        sentenceslist.append(senten)

                    # #print (text)
            else:
                html = get('http://%s'%(l),verify = False,headers = headers).text
                soup = BeautifulSoup(html)
                for script in soup(["script", "style"]):
                    script.extract()
                    # get text
                text = soup.get_text()
                # break into lines and remove leading and trailing space on each
                lines = (line.strip() for line in text.splitlines())
                # break multi-headlines into a line each
                chunks = (phrase.strip() for line in lines for phrase in line.split("  "))
                # drop blank lines
                text = '\n'.join(chunk for chunk in chunks if chunk)
                z = io.open('file1.txt','a', encoding="utf-8")
                z.write(text)
                z.close()
                z = io.open('media/%d.txt'%(rad),'a', encoding="utf-8")
                z.write(text)
                z.close()
                # #print(text)
                datalist.append(text)
                m = re.split(r'(?<=[^A-Z].[.?]) +(?=[A-Z])', text)
                for senten in m:
                    sentenceslist.append(senten)
            d1 = io.open('file1.txt','r', encoding="utf-8")

            file1_data = d1.read()
            file2_data = textss
            similarity_ratio.append(calplag(file1_data,file2_data)*100)
    #similarity_ratio = SequenceMatcher(None,file1_data,file2_data).ratio()
            d1.close()
            #print("\n\n\n\n")
            #print(randomfiles)
            # #print(sentenceslit)

    return similarity_ratio,datalist,sentenceslist,randomfiles



def geturls(req,text,x,filename):
    urllist = []
    abstractlist = []
    list3 = []
    count = len(re.findall(r'\w+', text))
    #print (count)



    # here we are scraping from google
    # raw = get("https://www.google.com/search?q=%s"%(text),headers = headers,verify=False).text
    # page = fromstring(raw)
    # for result in page.cssselect(".r a"):
    #     url = result.get("href")
    #     if url.startswith("/url?"):
    #         url = parse_qs(urlparse(url).query)['q']
    #     #print(url[0])
    #
    #     urllist.append(url[0].strip('https://'))
    # soup = BeautifulSoup(raw, "lxml")
    #
    # for s in soup.findAll('span', {'class': 'st'}):
    #     #print(s.text)
    #     abstractlist.append(s.text)111
    #     list3 = list(zip(urllist,abstractlist))
    # result = dataextract(urllist,text)
    # #print(list3)
    # #print('\n\n\n\nscrapped from google')


    if not list3:
        raw = get("http://www.ask.com/web?q=%s&o=0&qo=homepageSearchBox"%(text[:1000]),headers = headers,verify = False).text
        soup = BeautifulSoup(raw,'lxml')
        resultobj = soup.findAll('div', {'class': 'PartialSearchResults-item'})
        abstractobj = soup.findAll('p',{'class':'PartialSearchResults-item-abstract'})
        for resul in resultobj:
            resindex = resul.find('p')

checker/templates/base.html
 {% load staticfiles %}


 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
   <!--  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- link -->

    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
	<link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- </*script*/ src="../../assets/js/ie-emulation-modes-warning.js"></script> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>


    <![endif]-->

    <style type="text/css">
    .container-contact100 {
      width: 100%;
      min-height: 100vh;
      display: -webkit-box;
      display: -webkit-flex;
      display: -moz-box;
      display: -ms-flexbox;
      display: flex;
      flex-wrap: wrap;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      padding: 15px;
      background-repeat: no-repeat;
      background-position: center center;
      background-size: cover;
    }
    .wrap-contact100 {
      max-width: 960px;
      background: #fff;
      border-radius: 2px;
      padding: 66px 115px 59px 115px;
      position: relative;
    }

 .loader {
    border: 16px solid #f3f3f3; /* Light grey */
    border-top: 16px solid #3498db; /* Blue */
    border-radius: 50%;
    width: 120px;
    height: 120px;
    animation: spin 2s linear infinite;
}

@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}
a {
    color: black;
}

h1{
  font-size: 30px;
  color: #fff;
  text-transform: uppercase;
  font-weight: 300;
  text-align: center;
  margin-bottom: 15px;
}
table{
  width:100%;
  table-layout: fixed;
}
.tbl-header{
  background-color: rgba(255,255,255,0.3);
 }
.tbl-content{
  height:300px;
  overflow-x:auto;
  margin-top: 0px;
  border: 1px solid rgba(255,255,255,0.3);
}
th{
  padding: 20px 15px;
  text-align: left;
  font-weight: 500;
  font-size: 12px;
  color: #fff;
  text-transform: uppercase;
}
td{
  padding: 15px;
  text-align: center;
  vertical-align:middle;
  font-weight: 300;
  font-size: 12px;
  color: black;
  border-bottom: solid 1px rgba(255,255,255,0.1);
}


/* demo styles */

@import url(https://fonts.googleapis.com/css?family=Roboto:400,500,300,700);
body{
  background: -webkit-linear-gradient(left, #25c481, #25b7c4);
  background: linear-gradient(to right, #25c481, #25b7c4);
  font-family: 'Roboto', sans-serif;

}
section{
  margin: 50px;
}


/* follow me template */
.made-with-love {
  margin-top: 40px;
  padding: 10px;
  clear: left;
  text-align: center;
  font-size: 10px;
  font-family: arial;
  color: #fff;
}
.made-with-love i {
  font-style: normal;
  color: #F50057;
  font-size: 14px;
  position: relative;
  top: 2px;
}
.made-with-love a {
  color: #fff;
  text-decoration: none;
}
.made-with-love a:hover {
  text-decoration: underline;
}


/* for custom scrollbar for webkit browser*/

::-webkit-scrollbar {
    width: 6px;
}
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
::-webkit-scrollbar-thumb {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}



    </style>
  </head>

  <body>

    <!-- Static navbar
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>
            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div>/.nav-collapse
      </div>
    </nav> -->

	{% block content %}

	{% endblock content %}




    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>

  </body>
</html>

checker/templates/dash.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        {% block title %}{% endblock %}
        <title>Example Template</title>
        <!-- Bootstrap core CSS   /static/display/images/icons/favicon.ico-->
        {% load static %}
        <link rel="stylesheet" type="text/css" href="/static/dashboard/bootstrap/css/bootstrap.min.css" />
        <!-- Custom fonts for this template-->
        <link rel="stylesheet" type="text/css" href="static/dashboard/font-awesome/css/font-awesome.min.css" />
        <!-- Page level plugin CSS-->
        <link href="static/dashboard/vendor/datatables/dataTables.bootstrap4.css" />
        <!-- Custom styles for this template-->
        <link rel="stylesheet" type="text/css" href="static/dashboard/css/sb-admin.css" />
        <link rel="stylesheet" type="text/css" href="static/dashboard/css/custom.css" />
        {% block stylesheet %}{% endblock %}
    </head>

    <body class="fixed-nav sticky-footer bg-dark" id="page-top">
        <!-- Navigation-->
        {% include "elements/sidebar.html" %}
        <div class="content-wrapper">
            <!-- container-fluid-->
            {% block body %}{% endblock %}
            <!-- /.container-fluid-->
            <!-- /.content-wrapper-->
            <footer class="sticky-footer">
                <div class="container">
                    <div class="text-center">
                        <small>Copyright © Your Website 2018</small>
                    </div>
                </div>
            </footer>
            <!-- Scroll to Top Button-->
            <a class="scroll-to-top rounded" href="#page-top">
                <i class="fa fa-angle-up"></i>
            </a>
            <!-- Logout Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                            <a class="btn btn-primary" href="/logout">Logout</a>
                        </div>
                    </div>
                </div>
            </div>

            <!--Dynamic Javascript-->
            <script type="text/javascript" src="static/dashboard/jquery/jquery.min.js"></script>
            <script type="text/javascript" src="static/dashboard/bootstrap/js/bootstrap.bundle.min.js"></script>
            <!-- Core plugin JavaScript-->
            <script type="text/javascript" src="static/dashboard/jquery-easing/jquery.easing.min.js"></script>

            <!-- Page level plugin JavaScript-->

            {% block javascript %}{% endblock %}
        </div>
    </body>

</html>

checker/templates/display.html
{% extends 'footer.html' %}
{% block body %}
	<!DOCTYPE html>
<html lang="en">
<head>
	<title>Plagiarism Results</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="/static/display/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/display/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/display/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/display/vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/display/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/display/vendor/perfect-scrollbar/perfect-scrollbar.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/display/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/display/css/main.css">
<!--===============================================================================================-->

<style type="text/css">
	.scrollBox {
   height: 180px;
   width: 100%;
   border: 1px solid #ccc;
   overflow: auto;
   padding: 10px
 }
 body {background: #F0F0F0;}


h2 {margin-left: 55px;}

textarea {

  width: 100%;
  height: 380px;
  -moz-border-bottom-colors: none;
  -moz-border-left-colors: none;
  -moz-border-right-colors: none;
  -moz-border-top-colors: none;
  background: none repeat scroll 0 0 rgba(0, 0, 0, 0.07);
  border-color: -moz-use-text-color #FFFFFF #FFFFFF -moz-use-text-color;
  border-image: none;
  border-radius: 6px 6px 6px 6px;
  border-style: none solid solid none;
  border-width: medium 1px 1px medium;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.12) inset;
  color: #555555;
  font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
  font-size: 1em;
  line-height: 1.4em;
  padding: 5px 8px;
  transition: background-color 0.2s ease 0s;
}


textarea:focus {
    background: none repeat scroll 0 0 #FFFFFF;
    outline-width: 0;
}
</style>
</head>
<body>


	<div class="limiter">
		<div class="container-table100">
			<div class="wrap-table100">
				<center><h3>Plagiarism Result : {{result}} %</h3>
					</center>
				 <textarea  rows="20" name="comment[text]" id="comment_text" cols="40" class="ui-autocomplete-input" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">{{text}}</textarea>




				<div class="table100 ver2 m-b-110">

					<div class="table100-head">
						<table>
							<thead>
								<tr class="row100 head">
									<th class="cell100 column1">Sources</th>
									<th class="cell100 column2">Similarity Index</th>
									<th class="cell100 column3">View In Text</th>

								</tr>
							</thead>
						</table>
					</div>

					<div class="table100-body js-pscroll">
						<table>
							<tbody>


									{% for link in links %}
            <tr class="row100 body">


            <!-- <td align="center"><a href="http://{{l}}">{{l}}</a></td> -->
          <td class="cell100 column1"><a href="http://{{link.0}}">{{link.0}}</a></td>
            <!-- <td align="center">{{link.1}}</td>  -->
            <td class="cell100 column2">{{link.2}}</td>
									<td class="cell100 column3"><a href= '{% url 'checker:show' link.4  %}'>show</a></td>

            </tr>
          {% endfor %}


							</tbody>
						</table>
					</div>
				</div>

			</div>
		</div>
	</div>


<!--===============================================================================================-->
	<script src="/static/display/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/display/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/display/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/display/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/display/vendor/perfect-scrollbar/perfect-scrollbar.min.js"></script>
	<script>
		$('.js-pscroll').each(function(){
			var ps = new PerfectScrollbar(this);

			$(window).on('resize', function(){
				ps.update();
			})
		});


	</script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>

</body>
</html>
{% endblock %}

checker/templates/hello.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <p>hello world</p>
  </body>
</html>